# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

window_padding_width 10

modify_font cell_height 125%

# Fonts
# Nerd Fonts v3.1.0
font_family         JetBrainsMonoNL
bold_font           JetBrainsMonoNLExtraBold
bold_italic_font    JetBrainsMonoNLExtraBoldItalic
